spring:
  application:
    name: customer-service

  # Database configurations
  datasource:
    url: jdbc:h2:mem:customerDB
  h2:
    console:
      enabled: true

# Server configs
server:
  port: 8090
  ## Should be included to show message, if not error message will be empty
  error:
    include-message: always
    include-binding-errors: always

# Application health and information management
management:
  info.git:
    mode: full
    enabled: true
  endpoints.web.exposure.include: "*"
  endpoint:
    shutdown.enabled: false
    health.show-details: always

logging.level:
  org:
    springframework:
      web: DEBUG
    siriusxi:
      blueharvest:
        bank: DEBUG
  web: DEBUG
  root: INFO